// <auto-generated />
namespace FinanceManager.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MoneyOperations_InsteadOf_ExpensesAndIncomes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoneyOperations_InsteadOf_ExpensesAndIncomes));
        
        string IMigrationMetadata.Id
        {
            get { return "201707281508030_MoneyOperations_InsteadOf_ExpensesAndIncomes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
