// <auto-generated />
namespace FinanceManager.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nullablesettingid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nullablesettingid));
        
        string IMigrationMetadata.Id
        {
            get { return "201908061411430_Nullable-setting-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
